# PyTorch Basics

## 모듈 불러오기

In [0]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms


## Basic autograd example 1

#### Create tensors.

In [0]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

#### Build a computational graph.

![대체 텍스트](https://i.imgur.com/iUhWEj2.png)

In [0]:
y = w * x + b    # y = 2 * x + 3

#### Compute gradients.

In [4]:
# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


## 2. Basic autograd example 2

#### Create tensors of shape (10, 3) and (10, 2).

In [0]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)


#### 데이터 확인

In [6]:
print(x)
print(y)

tensor([[-1.1282e+00,  1.1983e+00,  1.5670e+00],
        [ 7.8507e-01,  1.6685e-01, -5.9059e-01],
        [-1.3745e+00,  8.5719e-01,  1.5289e+00],
        [-8.3842e-01, -3.5465e-01,  1.6365e+00],
        [-3.6387e-01,  1.1225e+00,  1.3041e+00],
        [-5.6778e-01, -1.3866e+00, -2.8627e+00],
        [-6.3000e-01,  1.8152e+00, -1.0477e+00],
        [ 1.5239e-01,  4.3888e-01, -2.6410e-01],
        [-7.6482e-01, -1.1244e+00, -2.5247e-03],
        [-9.6004e-01, -2.6096e-01,  9.1403e-01]])
tensor([[-0.8108,  0.7518],
        [ 2.9692,  0.0637],
        [ 0.5839,  1.6546],
        [-0.4771,  0.7938],
        [-1.0911, -0.2944],
        [-1.9389,  0.4978],
        [ 0.7001,  0.2896],
        [ 0.8992,  0.5689],
        [-1.4872, -0.7135],
        [ 0.3730,  1.4379]])


#### Build a fully connected layer.


In [7]:
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[0.3100, 0.2056, 0.1008],
        [0.1103, 0.0035, 0.3608]], requires_grad=True)
b:  Parameter containing:
tensor([-0.1090, -0.0372], requires_grad=True)


#### Build loss function and optimizer.

MSE:

$ℓ(x,y)=L=\{l_1,...,l_N\}^T,  l_n=(x_n-y_n)^2$

N 은 배치 크기

In [0]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

#### Forward pass

In [0]:
pred = linear(x)

In [10]:
print(pred)

tensor([[-0.0543,  0.4078],
        [ 0.1091, -0.1631],
        [-0.2046,  0.3657],
        [-0.2767,  0.4594],
        [ 0.1405,  0.3970],
        [-0.8587, -1.1375],
        [-0.0367, -0.4783],
        [ 0.0019, -0.1142],
        [-0.5774, -0.1265],
        [-0.3680,  0.1857]], grad_fn=<AddmmBackward>)


#### Compute loss.

In [11]:
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.1443209648132324


In [12]:
np.mean(np.square(pred.detach().numpy()-y.numpy()))

1.1443207

#### Backward pass.

In [0]:
loss.backward()

#### Print out the weights and gradients.

In [14]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[0.3100, 0.2056, 0.1008],
        [0.1103, 0.0035, 0.3608]], requires_grad=True)
b:  Parameter containing:
tensor([-0.1090, -0.0372], requires_grad=True)


In [15]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.2902, -0.2994,  0.0840],
        [ 0.4072, -0.0419,  0.2499]])
dL/db:  tensor([-0.1845, -0.5254])


#### 1-step gradient descent.

weight - learning_rate * gradient


In [16]:
linear.weight - 0.01 * linear.weight.grad

tensor([[0.3129, 0.2086, 0.1000],
        [0.1062, 0.0039, 0.3583]], grad_fn=<SubBackward0>)

In [0]:
optimizer.step()

In [18]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[0.3129, 0.2086, 0.1000],
        [0.1062, 0.0039, 0.3583]], requires_grad=True)
b:  Parameter containing:
tensor([-0.1071, -0.0320], requires_grad=True)


#### Print out the loss after 1-step gradient descent.

In [19]:
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.1371476650238037


##  3. Loading data from numpy

#### Create a numpy array.

In [0]:
x = np.array([[1, 2], [3, 4]])

#### Convert the numpy array to a torch tensor.

In [0]:
y = torch.from_numpy(x)

#### Convert the torch tensor to a numpy array.

In [0]:
z = y.numpy()